const INVITATION_TYPE = {
  INVITE_REQUEST: 'INVITE_REQUEST',
  INVITE_ACCEPT: 'INVITE_ACCEPT',
};

const INVITATION_RESPONSE_STATUS = {
  INVITING: 'INVITING',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  CANCEL: 'CANCEL',
};

const MEMBER_STYLE_TYPE = {
  DEFAULT: 'DEFAULT',
  SQUAD_DETIAL: 'SQUAD_DETAIL',
} as const;

export { INVITATION_RESPONSE_STATUS, INVITATION_TYPE, MEMBER_STYLE_TYPE };
