const INVITATION_TYPE = {
  INVITE_REQUEST: 'INVITE_REQUEST',
  INVITE_ACCEPT: 'INVITE_ACCEPT',
};

const INVITATION_RESPONSE_STATUS = {
  INVITING: 'INVITING',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  CANCEL: 'CANCEL',
};

export { INVITATION_RESPONSE_STATUS, INVITATION_TYPE };
