name: Sync with Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'Eggmeoni-na/scrumble-FE'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Organization Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.AUTO_ACTIONS }}

      - name: Push Upstream Main to Fork Main
        run: |
          git remote add fork https://x-access-token:${{ secrets.AUTO_ACTIONS }}@github.com/k-jeonghee/scrumble-FE.git
          git push fork main --force
