name: Sync with Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'k-jeonghee/scrumble-FE'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git user
        run: |
          git config --global user.name "k-jeonghee"
          git config --global user.email "heestory1992@gmail.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Eggmeoni-na/scrumble-FE.git
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git reset --hard upstream/main 
          git push origin main --force
