name: Sync Dev Branch with Upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream repository
        run: git remote add upstream https://github.com/Eggmeoni-na/scrumble-FE.git

      - name: Fetch upstream dev branch
        run: git fetch upstream dev

      - name: Merge upstream dev into fork dev
        run: |
          git checkout dev || git checkout -b dev
          git merge upstream/dev --allow-unrelated-histories
          git push origin dev
