name: Sync with Upstream

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'Eggmeoni-na/scrumble-FE'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Organization Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTO_ACTIONS }}

      - name: Add Fork Repository as Remote
        run: |
          git remote add fork https://x-access-token:${{ secrets.AUTO_ACTIONS }}@github.com/k-jeonghee/scrumble-FE.git

      - name: Sync Origin Main to Fork Main
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout main
          git pull origin main
          git push fork main --force

      - name: Sync Origin Dev to Fork Main
        if: github.ref == 'refs/heads/dev'
        run: |
          git checkout dev
          git pull origin dev
          git push fork dev:main --force
